### ISSUE TITLE
[bug] Wrong encoding for text field?

### ISSUE THREAD

**Issue by eightam** [antonlukin/sharing-image#17]
Umlauts and special characters don't seem to get encoded properly.

![2024-02-22_10-36-32@2x](https://github.com/antonlukin/sharing-image/assets/2012717/6375a9bb-37a7-4bd2-9b44-521a470aee24)

**Comment by antonlukin** [comment]
Hello @eightam 
Thank you for your ticket. I'll try to figure out the problem soon

**Comment by antonlukin** [comment]
I haven't been able to reproduce the problem yet. Can you send me the output of the `phpinfo()` command?

![Screenshot 2024-02-22 at 10 12 47](https://github.com/antonlukin/sharing-image/assets/454185/febec9ca-b2b3-4f0a-9411-4f09811db87a)

**Comment by simoneromboli** [comment]
hi there,
I've been experiencing the same issue.
A post has "Pùm" as title and the "ù" is missing as you can see here

![immagine](https://github.com/antonlukin/sharing-image/assets/99014113/0dbfe4ff-8e88-4358-954f-2ad8f81d0be2)

You'll find the [phpinfo here](https://paste.quest/?08a88e2b1713e642#Cnu9dy7M8VNeoFcjgWiZLFhTeGioJi3L91zfkGfgxyH8) - it's a shared hosting

Hope this helps,
thanks in advance

**Comment by eightam** [comment]
[Here you go](https://paste.quest/?26996218da9d1172#566mCFWyd5rWyNb138m6KZrDDEY3iE89B5XaKAuWDuUg).

I've tried many things already:
Checking the encoding of the string within the poster-editor component.
Updated the poster-editor compontent (are you using an older version on purpose in the wp plugin?).
Installing missing locales on the server.
Forcing UTF-8 on the string before rendering with imagefttext.

Nothing works.

I can make a staging copy of the installation if you want to analyse directly.

**Comment by antonlukin** [comment]
@eightam Thank you for your message.
I still can't reproduce this bug on my side. I've tried different php versions.
It would be really great if you could make a staging copy. This will allow me to try different fonts and so on.
You can send me sensitive data to support@wpset.org. 

(poster-editor will be updated in the next version soon)

**Comment by antonlukin** [comment]
@eightam  One more thing. 
Do I understand correctly that the problem persists even without using the plugin and without using poster-editor? Have you tried using `imagefttext` directly on your server configuration?
Or you can try to check out sample scripts from https://github.com/antonlukin/poster-editor. 
If the problem is related to `imagefttext` may be we could try to use another php version? 
I can also try to run your build on my side if you happen to be using docker.

And one more option – try loading an .otf font instead of .ttf.

I'm looking forward to your answer, and **thank you** for helping me get to the bottom of the truth.

**Comment by eightam** [comment]
Okay I see. This server has an issue. Even if I output UTF-8 text in imagefttext from a simple PHP example I'm getting errors. I will fix that first and then get back to you if it's solved. Thank you and sorry for the trouble!
